### ISSUE TITLE
Add more scrapping scripts 🎰 | NO LANGUAGE PREFERENCE

### ISSUE THREAD

**Issue by ab-anand** [ab-anand/scrapping#1]
Add your own Web scrapping script that you ever wrote. Please make sure that the code is readable 😋

**Comment by alexandrebarbaruiva** [comment]
Is there any language preference?

**Comment by ab-anand** [comment]
No. There is no any language preference @alexandrebarbaruiva

**Comment by amanagarwal97** [comment]
I wrote a script that will scrape all animes from MAL

**Comment by ab-anand** [comment]
Great! You can add it here @amanagarwal-sopho
